services:
  notification-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
